import random #just cuz
print("Mad Libs Generator")
print (' ')
print (' ')
print ("Hello let's play mad libs!")



adj1 = input("Tell me an Adjective & press enter ")
noun1 = input("Tell me an Noun & press enter ")
noun2 = input("Tell me an Noun & press enter ")
famous1 = input("Name a Famous Person & press enter ")
verb1 = input("Tell me an Verb & press enter ")
noun3 = input("Tell me an Noun & press enter ")
noun4 = input("Tell me an Noun & press enter ")
verb2 = input("Tell me an Verb & press enter ")
adj2 = input("Tell me an Adjective & press enter ")

print(' ')

print('When I walk on by, girls be looking like damn he ' + adj1)
print('I pimp to the beat,')
print('Walking on the street with in my new ' + noun1, ' yeah')
print('This is how I roll, animal print, pants out control,')
print("It's redfoo with the big" + noun2)
print("It's like famous1  rock at the club")
print(' ')
print('Girl look at that body')
print('Girl look at that body')
print('Girl look at that body')
print(' ')
print('I work out')
print(' ')
print('Girl look at that body')
print('Girl look at that body')
print('Girl look at that body')
print(' ')
print('I work out')
print(' ')
print('When I ' + verb1 + ' in the spot, this is what I see')
print('Everybody stops and they staring at me')
print('I got ' + noun3 + ' in my pants')
print("And I ain't afraid to show it, show it, show it, show it")
print(' ')
print("I'm " + noun4 + " and I know it")
print("I'm " + noun4 + " and I know it")
print(' ')
print("When I'm at the mall, security just can't " + verb2 + " 'em off")
print("When I'm at the beach, I'm in a speedo trying to tan my cheeks")
print("This is how I roll, come on ladies it's time to go")
print("We headed to the bar, baby don't be " + adj2)
print('No shoes, no shirt, and I still get serviced')
print(' ')
print('Girl look at that body')
print('Girl look at that body')
print('Girl look at that body')
print(' ')
print('I work out')
print(' ')
print('Girl look at that body')
print('Girl look at that body')
print('Girl look at that body')
print(' ')
print('I work out')
print(' ')
print('When I ' + verb1 + ' in the spot, this is what I see')
print('Everybody stops and they staring at me')
print('I got ' + noun3 + ' in my pants')
print("And I ain't afraid to show it, show it, show it, show it,")
print(' ')
print("I'm " + noun4 + " and I know it")
print("I'm " + noun4 + " and I know it")
print(' ')
print('Check it out, check it out')
print(' ')
print('Wiggle, wiggle, wiggle, wiggle, wiggle, wiggle, yeah')
print('Wiggle, wiggle, wiggle, wiggle, wiggle, wiggle, yeah')
print('Wiggle, wiggle, wiggle, wiggle, wiggle, wiggle, yeah')
print('Wiggle, wiggle, wiggle, wiggle, wiggle, wiggle, yeah')
print(' ')
print('Do the wiggle man')
print('Do the wiggle man')
print(' ')
print("I'm " + noun4 + " and I know it")
print(' ')
print('Girl look at that body')
print('Girl look at that body')
print('Girl look at that body')
print('')
print('I work out')
print(' ')
print('Girl look at that body')
print('Girl look at that body')
print('Girl look at that body, I work out')
print(' ')
print("I'm " + noun4 + " and I know it")


#just cuz
#just cuz
#just cuz
#just cuz
#just cuz
#just cuz

